spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://111.230.47.102/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 111.230.47.102
    port: 6379
    password: 123456

server:
  context-path: /sell

wechat:
  mpAppId: wxeded39f32f50adb2
  mpAppSecret: 784234fbf32b7f674257b7925a08e7e1
  openAppId: openAppId
  openAppSecret: openAppSecret
  mchId: mchId
  mchKey: mchKey
  keyPath: keyPath/h5.p12
  notifyUrl: http://fxoi.natapp1.cc/selll/pay/notify
  templateId:
    orderStatus: orderStatus

projectUrl:
  wechatMpAuthorize: http://fxoi.natapp1.cc
  wechatOpenAuthorize: http://fxoi.natapp1.cc
  sell: http://fxoi.natapp1.cc

logging:
  level:
    com.gittoy.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
