spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: some_pass
    url: jdbc:mysql://111.230.47.102:3306/sell?characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 111.230.47.102
    port: 6379
    password: 123456

server:
  context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 784234fbf32b7f674257b7925a08e7e1
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://fxoi.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: orderStatus

projectUrl:
  wechatMpAuthorize: http://fxoi.natapp1.cc
  wechatOpenAuthorize: http://fxoi.natapp1.cc
  sell: http://fxoi.natapp1.cc

logging:
  level:
    com.gittoy.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
