spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: some_pass
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

server:
  context-path: /sell

wechat:
  mpAppId: wx1902f6ed0e184846
  mpAppSecret: a5ba43e938f825f49be830a1531fb61a
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1501335121
  mchKey: ZHIHE18933320904ZWH18933320904CS
  keyPath: /var/weixin_cert/apiclient_cert.p12
  notifyUrl: http://fxoi.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: orderStatus

projectUrl:
  wechatMpAuthorize: http://fxoi.natapp4.cc
  wechatOpenAuthorize: http://fxoi.natapp4.cc
  sell: http://fxoi.natapp4.cc

logging:
  level:
    com.gittoy.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
  
spring.freemarker.request-context-attribute: request
